version: '3.9'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - database
    env_file:
      - .env  # Load environment variables
    ports:
      - "8080:8080"

volumes:
  pgdata:
